---
# Sanity Checks

- include_tasks: morpheus_sanity_checks.yml

- include_tasks: morpheus_packages_centos.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: morpheus_packages_ubuntu.yml
  when: ansible_os_family == 'Debian'

- include_tasks: morpheus_configure.yml