---
- name: Run Morpheus reconfigure one host at a time
  command: morpheus-ctl reconfigure
  args:
    creates: /etc/morpheus/morpheus-secrets.json
  async: 900
  poll: 10
  delegate_to: "{{ item }}"
  loop: "{{ groups[morpheus_group] }}"
  run_once: true

- name: Check for morpheus/ping
  uri:
    url: "https://{{ item }}/ping"
    return_content: true
    validate_certs: "{{ morpheus_validate_certs }}"
  register: urlcontent
  until: '"MORPHEUS PING" in urlcontent.content'
  retries: 30
  delay: 30
  loop: "{{ groups[morpheus_group] }}"
  run_once: true
